name: Deploy PHP to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync PHP App
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: Sync files to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftpupload.net
        username: if0_42980405
        password: purpleprada4
        local-dir: ./xampp/


        server-dir: ./htdocs/
        dangerously-allow-clean-all-remote-files: true
