name: Deploy PHP to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Sync PHP App
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Create production database configuration
        shell: bash
        run: |
          {
            echo "OPD_DB_HOST=${{ secrets.OPD_DB_HOST }}"
            echo "OPD_DB_NAME=${{ secrets.OPD_DB_NAME }}"
            echo "OPD_DB_USERNAME=${{ secrets.OPD_DB_USERNAME }}"
            echo "OPD_DB_PASSWORD=${{ secrets.OPD_DB_PASSWORD }}"
          } > .env

      - name: Upload to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: ./htdocs/
          state-name: .ftp-deploy-sync-state-live-v2.json
          log-level: standard
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github/**
